### ISSUE TITLE
can this work with diffusers?

### ISSUE THREAD

**Issue by dfl** [CFGpp-diffusion/CFGpp#2]
Can it work with diffusers lib? Will you release example code for that please?

**Comment by keturn** [comment]
The code in this repo _does_ use diffusers—but only the nn models, not the diffusers Pipeline or Scheduler.

I made some notes brainstorming here: https://github.com/invoke-ai/InvokeAI/issues/6516

**Comment by dfl** [comment]
thank you! oops, I did not examine close enough -- was on my phone's tiny screen and was looking at examples/text_to_img.py instead of latent_sdxl.py
