### ISSUE TITLE
import ipd breaks terminal

### ISSUE THREAD

**Issue by nagolinc** [CFGpp-diffusion/CFGpp#4]
this line seems wrong/not needed

https://github.com/CFGpp-diffusion/CFGpp/blob/main/examples/text_to_img.py#L47

also not sure why this for loop is here:

https://github.com/CFGpp-diffusion/CFGpp/blob/main/examples/text_to_img.py#L40

**Comment by CFGpp-diffusion** [comment]
Thanks for pointing it out.

https://github.com/CFGpp-diffusion/CFGpp/blob/ee909b5b41662c41d6fb585797a0710baf24d3f0/examples/text_to_img.py#L47

This was for debug. Now it is deleted.

https://github.com/CFGpp-diffusion/CFGpp/blob/ee909b5b41662c41d6fb585797a0710baf24d3f0/examples/text_to_img.py#L40

This was to reproduce our figure. Also, deleted.
